# Generated by Django 4.2.1 on 2023-06-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='select_timing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=12)),
                ('pickuptime', models.CharField(max_length=10)),
                ('droptime', models.CharField(max_length=10)),
                ('college', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
