# Generated by Django 4.2.1 on 2023-06-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_timings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timings',
            name='college',
            field=models.CharField(choices=[('VIIT Kondhwa', 'VIIT Kondhwa'), ('VIT Bibwewadi', 'VIT Bibwewadi'), ('PICT Dhanakawadi', 'PICT Dhanakawadi'), ('Bharati Vidyapeeth', 'Bharati Vidyapeeth')], max_length=50),
        ),
        migrations.AlterField(
            model_name='timings',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='timings',
            name='droptime',
            field=models.CharField(choices=[('1:00 PM', '1:00 PM'), ('2:00 PM', '2:00 PM'), ('3:00 PM', '3:00 PM'), ('4:00 PM', '4:00 PM'), ('5:00 PM', '5:00 PM'), ('6:00 PM', '6:00 PM')], max_length=20),
        ),
        migrations.AlterField(
            model_name='timings',
            name='pickuptime',
            field=models.CharField(choices=[('7:30 AM', '7:30 AM'), ('8:30 AM', '8:30 AM'), ('9:30 AM', '9:30 AM'), ('10:30 AM', '10:30 AM'), ('11:30 AM', '11:30 AM'), ('12:30 PM', '12:30 PM')], max_length=20),
        ),
    ]
