# Generated by Django 4.2.1 on 2023-06-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_timings_college_alter_timings_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
