# Generated by Django 4.2.1 on 2023-06-14 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_loginex'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='loginex',
            new_name='logins',
        ),
    ]
