# Generated by Django 4.2.1 on 2023-06-14 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_rename_loginex_logins'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logins',
        ),
        migrations.DeleteModel(
            name='select_timing',
        ),
        migrations.DeleteModel(
            name='timings',
        ),
    ]
